#+title: Network Simulator (NetSim)

* Getting Started

** Installation
1. Checkout NGO (com.unity.netcode.gameobjects) with the branch "develop".
2. Checkout UTP (com.unity.transport) with the branch "master".
3. Checkout Boss Room (com.unity.multiplayer.samples.coop).
4. Change Boss Room's manifest.json to point to the checked out versions of NGO and UTP. The branch "test/netsim-bossroom" can also be used and has the correct references.

** Configuration
1. Open Boss Room's "Startup" scene.
2. Find the NetworkManager gameobject. Open the foldout to find the UTP gameobject with a UnityTransport component attached.
3. Click on "Add Component" on the UTP gameobject and select "Network Simulator".
4. Save the scene and start the game.

Usage
- Ideally, run two instances of the Boss Room project with the network simulator enabled to see the best results.
- Click on "Disconnected" to ignore all sent and received data until "Connected" is clicked.
- Lag Spike does exactly the same thing, but re-enables the connection after the specified amount of time.
- Change the connection type to any of the presets to observe impacts of the network condition on the game.
- To create a custom preset and change the individual network parameters: In your project's asset folder, right click and select Create->ScriptableObject->NetworkSimulatorConfiguration. Select "Custom" as a connection type on the Network Simulator, and drag the created custom scriptable object into the new input field. Individual parameters are now editable and are saved to the scriptable object.
- Network scenarios can be used to automatically change simulator values at runtime. Some example scenarios are included, and custom ones can be created. With a custom scenario, an API is provided to access network simulator functionality, and custom properties can be added by the user and they will display in the network simulator Editor interface. When running, a scenario can be paused and resumed.

Note:
- This can be used on other project than Boss Room as well.